version: '3.8'

services:
    neo4j:
        image: neo4j:4.0
        ports:
            - "17687:7687"
        environment:
            - NEO4J_AUTH=neo4j/test
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true
            - NEO4JLABS_PLUGINS=["apoc"]
            - HTTP_PROXY=${HTTP_PROXY:-}
            - HTTPS_PROXY=${HTTPS_PROXY:-}
            - http_proxy=${http_proxy:-}
            - https_proxy=${https_proxy:-}

    agensgraph:
        image: turicas/agensgraph
        ports:
            - "5432"
        environment:
            - POSTGRES_USER=neo4j
            - POSTGRES_PASSWORD=test

    tests:
        image: ${MODNAME:-aiocypher}_unittest:${BUILD_TAG:-local}
        depends_on:
            - "neo4j"
            - "agensgraph"
        environment:
            - AGENSGRAPH_HOST=agensgraph
            - AGENSGRAPH_PORT=5432
