{%- set modname = "aiocypher" -%}
{%- import 'commontooling/docker/Dockerfile_multi_macros.j2' as macros -%}

{{ macros.preamble() }}

{{ macros.layer(modname, entrypoint=False) }}
# Install agensgraph extras as well so the tests pick them up
RUN --mount=type=cache,target=/root/.cache/pip --mount=type=secret,id=forgecert pip install -e .[agensgraph]

{{ macros.testdeps(modname) }}

{{ macros.tests(modname) }}

{{ macros.unittest(modname) }}
CMD ["-v"]

{{ macros.flake8(modname) }}

{{ macros.mypy(modname) }}

{{ macros.wheel(modname) }}
